version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/usr/src/app/
      - dependencies:/usr/src/app/node_modules
    restart: unless-stopped
    container_name: IBM_RCP_BackEnd
    ports:
      - 8080:8080
    command: yarn server

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8081

  mysqldb:
    platform: linux/x86_64
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: IBM_RCP_DATABASE
    ports:
      - 3306:3306

volumes:
  dependencies:
